# Generated by Django 2.2.8 on 2020-01-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200128_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='test_column',
        ),
    ]
