# Generated by Django 2.2.8 on 2020-01-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_portfolioimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
    ]
