# Generated by Django 2.2.8 on 2020-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200131_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('ticket_id', models.IntegerField(default=None)),
                ('ticket_route', models.CharField(default=None, max_length=256)),
                ('admin_message', models.TextField(default=None)),
                ('user_message', models.TextField(default=None)),
                ('is_user', models.IntegerField(default=None)),
            ],
        ),
    ]
