# Generated by Django 2.2.2 on 2020-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_postprojectimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprojectimages',
            name='project_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postprojectimages',
            name='project_image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='postprojectimages',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
