# Generated by Django 2.2.2 on 2020-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_projectimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprojectimages',
            name='project_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='postprojectimages',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
