# Generated by Django 2.2.2 on 2020-02-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200204_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
